# Generated by Django 5.0.3 on 2024-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('descricao_completa', models.TextField(verbose_name='')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
            ],
        ),
    ]
