# Generated by Django 5.0.3 on 2024-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='descricao_completa',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
