# Generated by Django 5.0 on 2024-04-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0004_tarefas_tarefa_para'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=50)),
                ('membros', models.ManyToManyField(related_name='equipes', to='usuario.usuario')),
            ],
        ),
    ]
