# Generated by Django 5.0 on 2024-04-17 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_equipe'),
        ('usuario', '0003_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa_para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
