# Generated by Django 5.0 on 2024-04-28 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0006_alter_tarefas_tarefa_para'),
        ('usuario', '0003_alter_usuario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='concluida',
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='tarefa_para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.equipe'),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='concluida',
            field=models.ManyToManyField(to='usuario.usuario'),
        ),
    ]
