# Generated by Django 5.0.3 on 2024-05-06 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_remove_tarefas_concluida_alter_tarefas_tarefa_para_and_more'),
        ('usuario', '0003_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_autor', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='concluida',
            field=models.ManyToManyField(blank=True, null=True, to='usuario.usuario'),
        ),
    ]
