# Generated by Django 5.0.3 on 2024-05-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0008_alter_tarefas_autor_alter_tarefas_concluida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefas',
            name='tarefa_para',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='tarefa_para',
            field=models.ManyToManyField(to='tarefas.equipe'),
        ),
    ]
