# Generated by Django 5.0.3 on 2024-05-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_remove_tarefas_tarefa_para_tarefas_tarefa_para'),
        ('usuario', '0003_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='alternativa1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='alternativa2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='alternativa3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='alternativa4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='alternativa5',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='alternativa_correta',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='concluida',
            field=models.ManyToManyField(blank=True, to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_limite',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
