# Generated by Django 5.0.3 on 2024-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0011_alter_tarefas_alternativa1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='alternativa_correta',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], null=True),
        ),
    ]
