# Generated by Django 5.0.3 on 2024-06-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_alter_tarefas_alternativa_correta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='alternativa_correta',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E')], default=1, null=True),
        ),
    ]
