# Generated by Django 5.0.3 on 2024-06-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0013_alter_tarefas_alternativa_correta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='resposta_usuario',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
