# Generated by Django 5.0.6 on 2024-07-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0015_alter_tarefas_resposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagem/tarefa/%Y/%m/%d/'),
        ),
    ]
