# Generated by Django 5.0.6 on 2024-07-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0016_tarefas_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_limite',
            field=models.DateTimeField(null=True, verbose_name='Data de Expiração'),
        ),
    ]
