# Generated by Django 5.0.6 on 2024-07-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0017_alter_tarefas_data_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='data_limite',
            field=models.DateTimeField(null=True),
        ),
    ]
