# Generated by Django 5.0.7 on 2024-07-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0019_mensagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='tipo_destino',
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='tarefas.equipe'),
        ),
    ]
