# Generated by Django 5.0.7 on 2024-07-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0020_remove_mensagem_tipo_destino_and_more'),
        ('usuario', '0003_alter_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='destinatarios',
            field=models.ManyToManyField(blank=True, related_name='mensagens_enviadas', to='tarefas.equipe'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='usuario.usuario'),
        ),
    ]
