# Generated by Django 5.0.7 on 2024-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0021_alter_mensagem_destinatarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='rascunho',
            field=models.BooleanField(default=True),
        ),
    ]
