# Generated by Django 5.0 on 2024-04-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('Aluno', 'Aluno'), ('Professor', 'Professor')], default='Aluno', max_length=9),
        ),
    ]
